# Generated by Django 6.0.4 on 2026-04-20 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationupdate',
            name='rider',
            field=models.ForeignKey(limit_choices_to={'role': 'rider'}, on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='locationupdate',
            index=models.Index(fields=['rider', 'order', '-timestamp'], name='tracking_lo_rider_i_6900d9_idx'),
        ),
    ]
