# Generated by Django 6.0.4 on 2026-04-24 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_placed', 'Order Placed'), ('payment_success', 'Payment Confirmed'), ('rider_assigned', 'Rider Assigned'), ('order_picked_up', 'Order Picked Up'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('new_order', 'New Order Available'), ('rating_received', 'Rating Received')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx')],
            },
        ),
    ]
